language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
script:
- platformio run
- rm ./.pioenvs
- rm ./.piolibdeps
- platformio run -e local
- "./.pioenvs/local/program"
